# Netlify configuration for Kimi Chat Next.js application
[build]
  command = "npm run build"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  # Redirect API key info to Moonshot platform
  from = "/api-key"
  to = "https://platform.moonshot.ai"
  status = 302